### ISSUE TITLE
[bug] Error activating VS Code extension v1.30.2 

### ISSUE THREAD

**Issue by jldec** [opral/monorepo#2192] opened 2024-02-07 19:22 UTC
### Problem

The extension is not loading for me (extension tab is blank, loading bar keeps loading) 
This is with a project which worked yesterday.

I see this error when I check the VS Code dev console.
```
Activating extension 'inlang.vs-code-extension' failed: ENV_DEFINED_IN_BUILD_STEP is not defined.
$onExtensionActivationError @ mainThreadExtensionService.ts:113
```

Rolling back to v.30.1 resolved the issue for me.

![Screenshot 2024-02-07 at 13 59 53](https://github.com/opral/monorepo/assets/849592/ca1efa3b-ca7e-4251-b6ee-8b4afbcb0b2e)

### Reproduction

upgrade VS Code to use the latest inlang extension

**Comment by samuelstroschein** [comment] 2024-02-07 19:24
i feel bad for @felixhaeberle. bugs keep coming in :D

**Comment by jldec** [comment] 2024-02-07 19:26
The new tab is really awesome. Example of missing translation below:

![Screenshot 2024-02-07 at 13 51 25](https://github.com/opral/monorepo/assets/849592/e4e83d15-05cc-465c-86e1-a5574577ac67)

**Comment by felixhaeberle** [comment] 2024-02-07 20:45
fix implemented in https://github.com/opral/monorepo/pull/2193

**Comment by samuelstroschein** [comment] 2024-02-07 21:01
*likely fix. couldn't reproduce it after the changes in #2193

**Comment by felixhaeberle** [comment] 2024-02-07 21:05
I'll verify in production. @jldec can you too? release is currently running in CI. should be available in 10min.

**Comment by felixhaeberle** [comment] 2024-02-07 21:15
<img width="603" alt="Bildschirmfoto 2024-02-07 um 22 15 01" src="https://github.com/opral/monorepo/assets/34959078/1a6bc20c-0e3f-42ed-89ec-a204ada3885f">

nope, still not fixed with version 1.31.0

**Comment by felixhaeberle** [comment] 2024-02-07 21:35
@samuelstroschein I found the issue. fix is underway.

**Comment by felixhaeberle** [comment] 2024-02-07 22:21
latest version v1.32.0 does fix the issue 👍 cc @jldec please reopen if not

**Closed by felixhaeberle** 2024-02-07 22:21 UTC
Labels: type: bug, scope: inlang/ide-extension
