### ISSUE TITLE
[bug] Can't `machine-translate` multiple new keys

### ISSUE THREAD

**Issue by jonator** [opral/monorepo#1968] opened 2024-01-04 14:35 UTC
### Problem

https://github.com/osmosis-labs/osmosis-frontend/pull/2639/commits/c564b8773ef5007e6d1b5130c3682b21132f30f6

See diff for this commit. I didn't notice as I thought it was fixed, but running machine-translate once seemed to generate the title, p1, and p3, but for some reason missed p2.

I'm wondering if it has to do with there being multiple new keys? Or the nesting?

Running multiple times as needed to get the remaining keys translated seems to work. 

### Expected behavior

Should generate translations for _all_ new keys in the ref file. Should not have to run multiple times.

### Reproduction

Add multiple new keys to the ref language file. Run machine translate. Notice some of the new keys are missing new translations.

### Other information

MacOS. Using JSON langage files.

**Comment by samuelstroschein** [comment] 2024-01-04 16:08
Shit. It's most likely this bug https://github.com/opral/monorepo/issues/1846 that I interim fixed with https://github.com/opral/monorepo/blob/c33736773d62e9f5036e32d33134e79d28e77bff/inlang/source-code/cli/src/commands/machine/translate.ts#L135. 

To quickly solve this bug, I will bumb the timeout to 8 seconds. I know ugly but an interim fix that should work. 

FYI We are hiring someone full-time to take care of the inlang SDK and squash bugs like these faster.

**Comment by jonator** [comment] 2024-01-04 17:39
Greetings to New York from Berlin. We switched seats 😂

**Comment by samuelstroschein** [comment] 2024-01-04 17:57
@jonator haha greetings from a wework in manhattan to berlin

**Comment by felixhaeberle** [comment] 2024-01-08 13:22
I will unassign myself from this issue in favor of https://github.com/opral/monorepo/issues/1846

**Comment by samuelstroschein** [comment] 2024-01-08 13:45
I will close this in favor of #1846

**Comment by samuelstroschein** [comment] 2024-01-09 04:12
The issue is likely not fixed. 

_From https://www.loom.com/share/fa5fb42050634398b0f588f7d167d2b6?highlightComment=28444086&t=142:_

> OMG. I just realized that the debounce (#1264) might be another cause why I needed to implement https://github.com/opral/monorepo/issues/1968#issuecomment-1877358306. 
>
> The debounce might have artificially extended the "duration" of saving files after machine translations have been created. Creating machine translations likely triggered write file multiple times all debounced. And now either the implementation queued all write files or dropped some. 
>
> OH SHIT. Most likely the debounce solution drops calls aka some write files were never executed aka some machine translations are not written to disk aka I have implemented the wrong fix for #1968. The real fix is an (async/reactive) state management system that can deal with backpressure ... adding this to the requirements

**Comment by samuelstroschein** [comment] 2024-01-09 04:24
@martin-lysk is your custom/removed debounce in #1844 ensured to not drop any write file calls and handle parallel write file calls?

The CLI machine translate command will execute CRUD operations in parallel, potentially triggering parallel writeFile calls. Parallel writeFile calls on the same file = very bad idea and will lead to bugs like this one. 

Another requirement for #1772 ... the solution needs to batch operations e.g. 100 machine translate have been created should only trigger one write file call.

**Comment by janfjohannes** [comment] 2024-01-10 21:00
@martin-lysk  im missing context a bit and am not sure where i was pinged here, do i need to do something?

**Comment by samuelstroschein** [comment] 2024-01-22 10:13
closing as stale (seems to be fixed)

**Closed by samuelstroschein** 2024-01-22 10:13 UTC
Labels: type: bug, scope: inlang/sdk, scope: inlang/cli
