### ISSUE TITLE
Pass project as url parameter to make project selection in `manage.fink.com` obsolete

### ISSUE THREAD

**Issue by felixhaeberle** [opral/monorepo#1998] opened 2024-01-10 14:32 UTC
### **Observation**

When clicking on "Settings" in Fink:

<img width="989" alt="Bildschirmfoto 2024-01-10 um 15 27 39" src="https://github.com/opral/monorepo/assets/34959078/52710219-8738-412e-a0cb-4b4b266df869">

you get redirected to:

<img width="1275" alt="Bildschirmfoto 2024-01-10 um 15 28 03" src="https://github.com/opral/monorepo/assets/34959078/8c86b9de-5736-4e39-820c-d25b62fbcfd4">

---

### **Proposal**

**This selection step is not necessary** because `manage.inlang.com` could simply take the `project` as an argument and then there is no manual selection needed here – you simply get redirected. 

like: `https://manage.inlang.com/?repo=github.com/inlang/monorepo?project="/project"`

Of course, this only applies to people coming from Fink where they already have a project selected.

**Comment by NiklasBuchfink** [comment] 2024-01-10 14:36
This already exists, otherwise it would not be possible to use the settings in FInk

**Comment by flornkm** [comment] 2024-01-10 14:37
@felixhaeberle @NiklasBuchfink I can validate, it is working for me:

https://github.com/opral/monorepo/assets/92092993/4e38a6f6-b8f1-46f2-9a51-f1ce9d2a664a

**Comment by NiklasBuchfink** [comment] 2024-01-10 14:38
@flornkm I think this only works, if you have only one inlang project. This is what @felixhaeberle is referring to.

**Comment by flornkm** [comment] 2024-01-10 14:48
@NiklasBuchfink can't we use the selected project to pass it into the URL? 🤔

**Comment by NiklasBuchfink** [comment] 2024-01-10 15:15
@flornkm The parameter of the project is not set for what ever reason. I'm working on that

**Comment by flornkm** [comment] 2024-01-10 16:05
@NiklasBuchfink it is weird. I cannot reproduce it, even in the monorepo with more than one project it inserts the correct project into the URL for me. 

@felixhaeberle what were the steps that you've taken? Asking because this issue may just appear if you edit a message or something.

**Comment by flornkm** [comment] 2024-01-11 14:44
> `https://manage.inlang.com/?repo=github.com/inlang/monorepo?project="/project"`

To be honest, this URL seems super wrong to me. In no query anywhere it is a practice to use two times the `?`, you should use `&` instead.

Fink automatically sets the correct URL params for you, and manage does that too.

If no one can reproduce that the URL mentioned above gets created, I will close this issue for now.
The correct URL looks like this: `https://manage.inlang.com/?repo=github.com/inlang/monorepo&project=/project.inlang`

**Comment by flornkm** [comment] 2024-01-11 14:44
Closing because can't reproduce and url was wrong

**Closed by flornkm** 2024-01-11 14:44 UTC
Labels: scope: inlang/fink-editor, scope: inlang/manage
